### ISSUE TITLE
bs-toaster is throwing exception for defaultIconMarkup

### ISSUE THREAD

**Issue by dhavalveera** [hummal/bs-toaster#2]
Hello,

I was experimenting the `bs-toaster` npm package in codepen to customize it a little-bit as per the my requirements, like adding custom icon, but when I used

```js
defaultIconMarkup: '<i class=""></i>
```

then it's throwing any error, even I tried by removing the `i` tag but still it's throwing an error.

please help me @hummal

**Comment by philipp-winterle** [comment]
can you please provide the error?

**Comment by philipp-winterle** [comment]
Can not reproduce:
I implemented font-awesome and used the markup. Everyting works fine. 

Maybe you should close your '' string

https://codepen.io/hummal/pen/RwZOowY

**Comment by dhavalveera** [comment]
and I can use only FontAwesome in `defaultIconMarkup` or can use any other as well which provide `<i></i>` tag icons?
