### ISSUE TITLE
is the ToasterType affect the background color ?

### ISSUE THREAD

**Issue by JERRYZFC** [hummal/bs-toaster#3]
hello hummal
thanks for your wonderful work,
but can the ToasterType  change the background color of the toaster?
I changed the type from your codepen demo but nothing work ,
https://codepen.io/hummal/pen/RwZOowY

**Comment by philipp-winterle** [comment]
Hello @JERRYZFC,

thanks for your question.

The ToasterType itself should change the color of the ICON in front of the toast title. Not the background of the toast itself. 

I updated the example to give you more different Toasts you can create
