### ISSUE TITLE
peedDependacy change to allow bootstrap version 5.2.0-beta1

### ISSUE THREAD

**Issue by phinett** [hummal/bs-toaster#4]
I'm not sure if possible, but if you could modify it so npm will allow me to add bs-toaster with bootstra 5.2.0-beta1 installed this would be great.

**Comment by philipp-winterle** [comment]
I need to test it and if it works I will make a release. :)

**Comment by philipp-winterle** [comment]
You could also use `--legacy-peer-deps` when doing npm install to ignore peerDependecies. 
As I read the problem would be that I have to add every single beta version of a package as a peer dependency. Which would result in another request of including beta2

**Comment by philipp-winterle** [comment]
should be no problem anymore since 5.2.0 is released
