### ISSUE TITLE
Couldn’t for the life of me get it to work on a hosting provider (no nodejs)

### ISSUE THREAD

**Issue by MikeJustMikeFMichael** [hummal/bs-toaster#5]
I ended up adapting your code to the Below. Don’t laugh. But it works like a charm for a no module approach

function bsToaster(bsToasterTitle, bsToasterText, bsToasterIcon) {

    const TOAST_CONTAINER_TEMLATE = `
	  <div data-bs-toaster="" class="toast-container position-fixed p-3"></div>  
	`;

    const TOAST_TEMPLATE = `
	  <div class="toast align-items-center text-bg-dark border-0 bg-opacity-100" role="alert" aria-live="assertive" aria-atomic="true">
		<div class="toast-header text-bg-dark">
		 <span class="bs-toaster-icon d-flex">%ICON%</span>
		  <strong class="bs-toaster-title me-auto"></strong>
		  <small class="text-white">Just Now</small>
		  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
		</div>
		<div class="bs-toaster-text toast-body"></div>
	  </div>
	`;

    const DEFAULT_ICON_MARKUP = `
	  <i class="p-2 me-2 rounded %TYPE%"></i>
	`;

    iconMarkup = DEFAULT_ICON_MARKUP;

    const position = "top-0 end-0";

    const base64Position = btoa(position);

    const existingToastContainer = document.querySelector(
        `[data-bs-toaster="${base64Position}"]`
    );

    let containerNode = null;

    if (
        existingToastContainer === null ||
        existingToastContainer instanceof HTMLDivElement === false
    ) {
        containerNode = new DOMParser().parseFromString(
            TOAST_CONTAINER_TEMLATE,
            "text/html"
        ).body.childNodes[0];

        containerNode.classList.add(...position.split(" "));

        containerNode.dataset.bsToaster = base64Position;
    } else {
        containerNode = existingToastContainer;
    }

    templateNode = null;
    toastContainer = null;

    this.toastContainer = containerNode;
    this.templateNode = new DOMParser().parseFromString(TOAST_TEMPLATE, "text/html").body.childNodes[0];

    document.body.appendChild(this.toastContainer);

    const toastNode = this.templateNode.cloneNode(true);

    toastNode.dataset.bsAutohide = "true"
    toastNode.dataset.bsDelay = "3000";
    toastNode.dataset.bsAnimation = "true";

    const iconNode = toastNode.querySelector(".bs-toaster-icon");
    if (iconMarkup) {
        iconMarkup = iconMarkup.replace("%TYPE%", bsToasterIcon);
        iconNode.innerHTML = iconMarkup;
    } else {
        iconNode.remove();
    }

    toastNode.querySelector(".bs-toaster-title").innerHTML = bsToasterTitle;
    toastNode.querySelector(".bs-toaster-text").innerHTML = bsToasterText;

    this.toastContainer.appendChild(toastNode);

    const toast = new bootstrap.Toast(toastNode);
    toast.show();
`}```

**Comment by philipp-winterle** [comment]
👯 
You don't use this as a node module on your webhost. You build your JavaScript with a bundler, which then imports this code into browser JavaScript and then use it in the browser. This would not use any import statements anymore. 👍🏻 

Your approach is different 🤣

**Comment by philipp-winterle** [comment]
Added a Toaster.bundle.js to the dist folder. Maybe this will fit your needs

**Comment by philipp-winterle** [comment]
https://github.com/hummal/bs-toaster/releases/tag/1.0.5
