### ISSUE TITLE
Console error "Uncaught SyntaxError: export declarations may only appear at top level of a module"

### ISSUE THREAD

**Issue by mmssix** [hummal/bs-toaster#6]
**Describe the bug**
Simple import of the "Toaster.bundle.js" as outlined in the readme causes an error in the console.

**To Reproduce**
1) Downloaded package from github
2) Unzipped
3) Took the "Toaster.bundle.js" file and copied it to my static folder (flask project)
4) imported with `<script src="{{ url_for('static', filename='base/Toaster.bundle.js') }}"></script>`
5) Got this error in the firefox console: "Uncaught SyntaxError: export declarations may only appear at top level of a module"

**Expected behavior**
Clean load

**Screenshots**
https://imgur.com/a/6tQTgNe

**Desktop (please complete the following information):**
 - OS: Linux mint
 - Browser: Firefox

**Comment by philipp-winterle** [comment]
Hello @mmssix. 

If I got you right: You want to use this script with a script tag in your html? 
Iam sorry, to tell you that this won't work. 
bs.-toaster is intended to be uses as an ES Import and may also work as a Common JS but not as you did. 

You should write a js file and import bs-toaster as shown in the readme. With your bundler you will resolve those imports and transpile it into a bundle you can import in your script tag in HTML. 

So this is not a bug.

**Comment by mmssix** [comment]
For any that may come after - What he meant to say is that the import of this one is slightly different.  Its not a normal js "<script>" type declaration (which I would have seen if I had looked closer at the example...)
 
The "type=module" is the important bit.  First time seeing that myself:  
`<script type="module"> import { Toaster, blah, blah }`

https://github.com/hummal/bs-toaster/blob/master/examples/simple.html#L13
